# Change these first
owner: serversshnet # Your GitHub organization or username, where this repository lives
repo: server-status # The name of this repository

sites:
 - name: Serverssh.net - Website
   check: "tcp-ping"
   url: serverssh.net
 - name: sg1.serverssh.net
   check: "tcp-ping"
   url: sg1.serverssh.net
 - name: sg2.serverssh.net
   check: "tcp-ping"
   url: sg2.serverssh.net
 - name: sg3.serverssh.net
   check: "tcp-ping"
   url: sg3.serverssh.net
 - name: sgx1.serverssh.net
   check: "tcp-ping"
   url: sgx1.serverssh.net
 - name: sgx2.serverssh.net
   check: "tcp-ping"
   url: sgx2.serverssh.net
 - name: sgm1.serverssh.net
   check: "tcp-ping"
   url: sgm1.serverssh.net
 - name: sgm2.serverssh.net
   check: "tcp-ping"
   url: sgm2.serverssh.net
 - name: sgm3.serverssh.net
   check: "tcp-ping"
   url: sgm3.serverssh.net
 - name: sg1socks.serverssh.net
   check: "tcp-ping"
   url: sg1socks.serverssh.net
 - name: sgx3.serverssh.net
   check: "tcp-ping"
   url: sgx3.serverssh.net
 - name: sg2socks.serverssh.net
   check: "tcp-ping"
   url: sg2socks.serverssh.net
 - name: sg1ray.serverip.my.id
   check: "tcp-ping"
   url: sg1ray.serverip.my.id
 - name: sg2ray.serverip.my.id
   check: "tcp-ping"
   url: sg2ray.serverip.my.id
 - name: sg3ray.serverip.my.id
   check: "tcp-ping"
   url: sg3ray.serverip.my.id
 - name: ukray.serverip.my.id
   check: "tcp-ping"
   url: ukray.serverip.my.id
 - name: caray.serverip.my.id
   check: "tcp-ping"
   url: caray.serverip.my.id
 - name: sg1vpn.serverssh.net
   check: "tcp-ping"
   url: sg1vpn.serverssh.net
 - name: sg2vpn.serverssh.net
   check: "tcp-ping"
   url: sg2vpn.serverssh.net
 - name: ca.serverssh.net
   check: "tcp-ping"
   url: ca.serverssh.net
 - name: sg1ray.serverssh.net
   check: "tcp-ping"
   url: sg1ray.serverssh.net
 - name: geray.serverip.my.id
   check: "tcp-ping"
   url: geray.serverip.my.id
 - name: ge.serverssh.net
   check: "tcp-ping"
   url: ge.serverssh.net
 - name: fr.serverssh.net
   check: "tcp-ping"
   url: fr.serverssh.net
 - name: po.serverssh.net
   check: "tcp-ping"
   url: po.serverssh.net
 - name: cax.serverssh.net
   check: "tcp-ping"
   url: cax.serverssh.net
 - name: frx.serverssh.net
   check: "tcp-ping"
   url: frx.serverssh.net
 - name: plx.serverssh.net
   check: "tcp-ping"
   url: plx.serverssh.net
 - name: dex.serverssh.net
   check: "tcp-ping"
   url: dex.serverssh.net
 - name: sgm4.serverssh.net
   check: "tcp-ping"
   url: sgm4.serverssh.net
 - name: sgm5.serverssh.net
   check: "tcp-ping"
   url: sgm5.serverssh.net
 - name: sgm6.serverssh.net
   check: "tcp-ping"
   url: sgm6.serverssh.net
 - name: sgm1ray.serverip.my.id
   check: "tcp-ping"
   url: sgm1ray.serverip.my.id
 - name: sg3ray.serverssh.net
   check: "tcp-ping"
   url: sg3ray.serverssh.net
 - name: sg1.serverssh.net
   check: "tcp-ping"
   url: sg1.serverssh.net
 - name: sg2.serverssh.net
   check: "tcp-ping"
   url: sg2.serverssh.net
 - name: ca.serverssh.net
   check: "tcp-ping"
   url: ca.serverssh.net
 - name: fr.serverssh.net
   check: "tcp-ping"
   url: fr.serverssh.net
 - name: ge.serverssh.net
   check: "tcp-ping"
   url: ge.serverssh.net
 - name: ukray.serverssh.net
   check: "tcp-ping"
   url: ukray.serverssh.net
 - name: sg1grpc.serverip.my.id
   check: "tcp-ping"
   url: sg1grpc.serverip.my.id
 - name: sg2grpc.serverip.my.id
   check: "tcp-ping"
   url: sg2grpc.serverip.my.id
 - name: ca1grpc.serverip.my.id
   check: "tcp-ping"
   url: ca1grpc.serverip.my.id
 - name: degrpc.serverip.my.id
   check: "tcp-ping"
   url: degrpc.serverip.my.id
 - name: ukgrpc.serverip.my.id
   check: "tcp-ping"
   url: ukgrpc.serverip.my.id
 - name: sgmgrpc.serverip.my.id
   check: "tcp-ping"
   url: sgmgrpc.serverip.my.id
 - name: sg1ray.serverip.my.id
   check: "tcp-ping"
   url: sg1ray.serverip.my.id
 - name: sg2ray.serverip.my.id
   check: "tcp-ping"
   url: sg2ray.serverip.my.id
 - name: sg3ray.serverip.my.id
   check: "tcp-ping"
   url: sg3ray.serverip.my.id
 - name: ukray.serverip.my.id
   check: "tcp-ping"
   url: ukray.serverip.my.id
 - name: caray.serverip.my.id
   check: "tcp-ping"
   url: caray.serverip.my.id
 - name: geray.serverip.my.id
   check: "tcp-ping"
   url: geray.serverip.my.id
 - name: sgm1ray.serverip.my.id
   check: "tcp-ping"
   url: sgm1ray.serverip.my.id

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.serverssh.net
  # baseUrl: /
  logoUrl: https://serverssh.net/assets/img/brand/favicon.png
  name: Serverssh.net
  favicon: https://serverssh.net/assets/img/brand/favicon.png
  introTitle: "Monitor server status for services on serverssh.net"
  introMessage: This is a server status page that uses real-time data
  navbar:
    - title: Home
      href: https://serverssh.net
  theme: ocean
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
