# Change these first
owner: serversshnet # Your GitHub organization or username, where this repository lives
repo: server-status # The name of this repository

sites:
  - name: Serverssh
    url: https://serverssh.net/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 200
  - name: idtr.jagoan.vip
    url: http://idtr.jagoan.vip/http://
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: id2tr.jagoan.vip
    url: http://id2tr.jagoan.vip/http://
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: id3tr.jagoan.vip
    url: http://id3tr.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: id4tr.jagoan.vip
    url: http://id4tr.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: id5tr.jagoan.vip
    url: http://id5tr.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: id6tr.jagoan.vip
    url: http://id6tr.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sgtr.jagoan.vip
    url: http://sgtr.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sg2tr.jagoan.vip
    url: http://sg2tr.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sg3tr.jagoan.vip
    url: http://sg3tr.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: biztr.jagoan.vip
    url: http://biztr.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: biz2tr.jagoan.vip
    url: http://biz2tr.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: idray.jagoan.vip
    url: http://idray.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: id2ray.jagoan.vip
    url: http://id2ray.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: id3ray.jagoan.vip
    url: http://id3ray.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: bizray.jagoan.vip
    url: http://bizray.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: biz2ray.jagoan.vip
    url: http://biz2ray.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: sgray.jagoan.vip
    url: http://sgray.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sg2ray.jagoan.vip
    url: http://sg2ray.jagoan.vip/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: vvip.ipservers.xyz
    url: http://vvip.ipservers.xyz:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sg2vvip.ipservers.xyz
    url: http://sg2vvip.ipservers.xyz:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: sg3vvip.ipservers.xyz
    url: http://sg3vvip.ipservers.xyz:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: idvvip.ipservers.xyz
    url: http://idvvip.ipservers.xyz:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: id2vvip.ipservers.xyz
    url: http://id2vvip.ipservers.xyz:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: id3vvip.ipservers.xyz
    url: http://id3vvip.ipservers.xyz:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: id4vvip.ipservers.xyz
    url: http://id4vvip.ipservers.xyz:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: id5vvip.ipservers.xyz
    url: http://id5vvip.ipservers.xyz:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: sby.ipservers.xyz
    url: http://sby.ipservers.xyz:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: biznet.ipservers.xyz
    url: http://biznet.ipservers.xyz:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: biznet2.ipservers.xyz
    url: http://biznet2.ipservers.xyz:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: sgltp.ipservers.xyz
    url: http://sgltp.ipservers.xyz:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: idltp.ipservers.xyz
    url: http://idltp.ipservers.xyz:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.serverssh.net
  # baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Monitor server status for jagoanssh and serversh."
  introMessage: This is a server status page that uses real-time data from.
  navbar:
    - title: Serverssh
      href: https://serverssh.net
  theme: dark
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
#  graphs: "*/5 * * * *"
#  responseTime: "*/5 * * * *"
#  staticSite: "*/5 * * * *"
#  summary: "*/5 * * * *"
#  updateTemplate: "*/5 * * * *"
#  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
