# Change these first
owner: serversshnet # Your GitHub organization or username, where this repository lives
repo: server-status # The name of this repository

sites:
  - name: Serverssh.net
    check: "tcp-ping"
    url: serverssh.net
  - name: sg1ray.serverssh.net
    url: sg1ray.serverssh.net
    check: "tcp-ping"
  - name: sg2ray.serverssh.net
    check: "tcp-ping"
    url: sg2ray.serverssh.net
  - name: sg3ray.serverssh.net
    check: "tcp-ping"
    url: sg3ray.serverssh.net
  - name: ukray.serverssh.net
    check: "tcp-ping"
    url: ukray.serverssh.net
  - name: ca1ray.serverssh.net
    check: "tcp-ping"
    url: ca1ray.serverssh.net
  - name: geray.serverssh.net
    check: "tcp-ping"
    url: geray.serverssh.net
  - name: sgm1ray.serverssh.net
    check: "tcp-ping"
    url: sgm1ray.serverssh.net
  - name: sg1grpc.serverssh.us
    check: "tcp-ping"
    url: sg1grpc.serverssh.us
  - name: sg2grpc.serverssh.us
    check: "tcp-ping"
    url: sg2grpc.serverssh.us
  - name: ca1grpc.serverssh.us
    url: ca1grpc.serverssh.us
    check: "tcp-ping"
  - name: degrpc.serverssh.us
    url: degrpc.serverssh.us
    check: "tcp-ping"
  - name: ukgrpc.serverssh.us
    url: ukgrpc.serverssh.us
    check: "tcp-ping"
  - name: sgmgrpc.serverssh.us
    url: sgmgrpc.serverssh.us
    check: "tcp-ping"
  - name: sg1.serverssh.net
    url: sg1.serverssh.net
    check: "tcp-ping"
  - name: sg2.serverssh.net
    url: sg2.serverssh.net
    check: "tcp-ping"
  - name: sg3.serverssh.net
    url: sg3.serverssh.net
    check: "tcp-ping"
  - name: ca.serverssh.net
    url: http://ca.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: ge.serverssh.net
    url: http://ge.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: fr.serverssh.net
    url: http://fr.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: po.serverssh.net
    url: http://po.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: SG1 SLOW DNS
    url: http://sg1.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: SG2 SLOW DNS
    url: http://sg2.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: CA SLOW DNS
    url: http://ca.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: FR SLOW DNS
    url: http://fr.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: GE SLOW DNS
    url: http://ge.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: UK SLOW DNS
    url: http://ukray.serverssh.net/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: SGX SLOW DNS
    url: http://sg1ray.serverssh.net/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301 
  - name: SG2X SLOW DNS
    url: http://sg3ray.serverssh.net/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sgx1.serverssh.net
    url: http://sgx1.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sgx2.serverssh.net
    url: http://sgx2.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: cax.serverssh.net
    url: http://cax.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: plx.serverssh.net
    url: http://plx.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: dex.serverssh.net
    url: http://dex.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sgm1.serverssh.net
    url: http://sgm1.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sgm2.serverssh.net
    url: http://sgm2.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sgm3.serverssh.net
    url: http://sgm3.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sgm4.serverssh.net
    url: http://sgm4.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sgm5.serverssh.net
    url: http://sgm5.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sgm6.serverssh.net
    url: http://sgm6.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sg1vpn.serverssh.net
    url: http://sg1vpn.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sg2vpn.serverssh.net
    url: http://sg2vpn.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sg1socks.serverssh.net
    url: http://sg1socks.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301
  - name: sg2socks.serverssh.net
    url: http://sg2socks.serverssh.net:10000/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 400
     - 200
     - 301

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.serverssh.net
  # baseUrl: /
  logoUrl: https://serverssh.net/assets/img/brand/favicon.png
  name: Serverssh.net
  favicon: https://serverssh.net/assets/img/brand/favicon.png
  introTitle: "Monitor server status for services on serverssh.net"
  introMessage: This is a server status page that uses real-time data
  navbar:
    - title: Home
      href: https://serverssh.net
  theme: ocean
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
