# Change these first
owner: serversshnet # Your GitHub organization or username, where this repository lives
repo: server-status # The name of this repository

sites:
  - name: Serverssh
    url: https://serverssh.net/
    maxResponseTime: 5000
    expectedStatusCodes:
     - 200
  - name: Jagoanssh
    url: https://www.jagoanssh.com
    maxResponseTime: 5000
    expectedStatusCodes:
     - 200
    __dangerous__insecure: true
  - name: idtr.jagoan.vip
    url: idtr.jagoan.vip
  - name: id2tr.jagoan.vip
    url: id2tr.jagoan.vip

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.serverssh.net
  # baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Monitor server status for jagoanssh and serversh."
  introMessage: This is a server status page that uses real-time data from.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/5 * * * *"
  summary: "*/5 * * * *"
  updateTemplate: "*/5 * * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
